// Code generated by go-bindata.
// sources:
// templates/home.html
// templates/index.html
// templates/page.html
// templates/post.html
// DO NOT EDIT!

package tpl

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io"
	"strings"
	"os"
	"time"
	"io/ioutil"
	"path"
	"path/filepath"
)

func bindataRead(data []byte, name string) ([]byte, error) {
	gz, err := gzip.NewReader(bytes.NewBuffer(data))
	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}

	var buf bytes.Buffer
	_, err = io.Copy(&buf, gz)
	clErr := gz.Close()

	if err != nil {
		return nil, fmt.Errorf("Read %q: %v", name, err)
	}
	if clErr != nil {
		return nil, err
	}

	return buf.Bytes(), nil
}

type asset struct {
	bytes []byte
	info  os.FileInfo
}

type bindataFileInfo struct {
	name string
	size int64
	mode os.FileMode
	modTime time.Time
}

func (fi bindataFileInfo) Name() string {
	return fi.name
}
func (fi bindataFileInfo) Size() int64 {
	return fi.size
}
func (fi bindataFileInfo) Mode() os.FileMode {
	return fi.mode
}
func (fi bindataFileInfo) ModTime() time.Time {
	return fi.modTime
}
func (fi bindataFileInfo) IsDir() bool {
	return false
}
func (fi bindataFileInfo) Sys() interface{} {
	return nil
}

var _homeHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9\xcd\xb1\xe3\xb2\x81\x51\xa9\x89\x29\x0a\x39\x89\x79\xe9\xb6\x4a\xa9\x79\x4a\x76\x5c\x0a\x40\x60\x93\x9b\x5a\x92\xa8\x90\x9c\x91\x58\x54\x9c\x5a\x62\xab\x14\x1a\xe2\xa6\x6b\x01\x93\x2a\xc9\x2c\xc9\x49\xb5\xb3\xd1\x87\xd0\x5c\x36\xfa\x20\x03\x80\x74\x52\x7e\x4a\xa5\x1d\x17\x90\x0f\x61\x00\xc5\x41\xe6\x03\x02\x00\x00\xff\xff\x27\xec\xda\x28\x76\x00\x00\x00")

func homeHtmlBytes() ([]byte, error) {
	return bindataRead(
		_homeHtml,
		"home.html",
	)
}

func homeHtml() (*asset, error) {
	bytes, err := homeHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "home.html", size: 118, mode: os.FileMode(420), modTime: time.Unix(1439665071, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _indexHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9\xcd\xb1\xe3\xb2\x81\x51\xa9\x89\x29\x0a\x39\x89\x79\xe9\xb6\x4a\xa9\x79\x4a\x76\x5c\x0a\x40\x60\x93\x9b\x5a\x92\xa8\x90\x9c\x91\x58\x54\x9c\x5a\x62\xab\x14\x1a\xe2\xa6\x6b\x01\x93\x2a\xc9\x2c\xc9\x49\xb5\xb3\xd1\x87\xd0\x5c\x36\xfa\x20\x03\x80\x74\x52\x7e\x4a\xa5\x1d\x17\x90\x0f\x61\x00\xc5\x41\xe6\x03\x02\x00\x00\xff\xff\x27\xec\xda\x28\x76\x00\x00\x00")

func indexHtmlBytes() ([]byte, error) {
	return bindataRead(
		_indexHtml,
		"index.html",
	)
}

func indexHtml() (*asset, error) {
	bytes, err := indexHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "index.html", size: 118, mode: os.FileMode(420), modTime: time.Unix(1439665071, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _pageHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xb2\x51\x74\xf1\x77\x0e\x89\x0c\x70\x55\xc8\x28\xc9\xcd\xb1\xe3\xb2\x81\x51\xa9\x89\x29\x0a\x39\x89\x79\xe9\xb6\x4a\xa9\x79\x4a\x76\x5c\x0a\x40\x60\x93\x9b\x5a\x92\xa8\x90\x9c\x91\x58\x54\x9c\x5a\x62\xab\x14\x1a\xe2\xa6\x6b\x01\x93\x2a\xc9\x2c\xc9\x49\xb5\xb3\xd1\x87\xd0\x5c\x36\xfa\x20\x03\x80\x74\x52\x7e\x4a\xa5\x1d\x17\x90\x0f\x61\x00\xc5\x41\xe6\x03\x02\x00\x00\xff\xff\x27\xec\xda\x28\x76\x00\x00\x00")

func pageHtmlBytes() ([]byte, error) {
	return bindataRead(
		_pageHtml,
		"page.html",
	)
}

func pageHtml() (*asset, error) {
	bytes, err := pageHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "page.html", size: 118, mode: os.FileMode(420), modTime: time.Unix(1439665071, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

var _postHtml = []byte("\x1f\x8b\x08\x00\x00\x09\x6e\x88\x00\xff\xaa\xae\xd6\x0b\x48\x4c\x4f\xd5\x73\xca\x4f\xa9\xac\xad\x05\x04\x00\x00\xff\xff\xfd\xfa\x72\xa3\x0e\x00\x00\x00")

func postHtmlBytes() ([]byte, error) {
	return bindataRead(
		_postHtml,
		"post.html",
	)
}

func postHtml() (*asset, error) {
	bytes, err := postHtmlBytes()
	if err != nil {
		return nil, err
	}

	info := bindataFileInfo{name: "post.html", size: 14, mode: os.FileMode(420), modTime: time.Unix(1439753766, 0)}
	a := &asset{bytes: bytes, info:  info}
	return a, nil
}

// Asset loads and returns the asset for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func Asset(name string) ([]byte, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("Asset %s can't read by error: %v", name, err)
		}
		return a.bytes, nil
	}
	return nil, fmt.Errorf("Asset %s not found", name)
}

// MustAsset is like Asset but panics when Asset would return an error.
// It simplifies safe initialization of global variables.
func MustAsset(name string) []byte {
	a, err := Asset(name)
	if (err != nil) {
		panic("asset: Asset(" + name + "): " + err.Error())
	}

	return a
}

// AssetInfo loads and returns the asset info for the given name.
// It returns an error if the asset could not be found or
// could not be loaded.
func AssetInfo(name string) (os.FileInfo, error) {
	cannonicalName := strings.Replace(name, "\\", "/", -1)
	if f, ok := _bindata[cannonicalName]; ok {
		a, err := f()
		if err != nil {
			return nil, fmt.Errorf("AssetInfo %s can't read by error: %v", name, err)
		}
		return a.info, nil
	}
	return nil, fmt.Errorf("AssetInfo %s not found", name)
}

// AssetNames returns the names of the assets.
func AssetNames() []string {
	names := make([]string, 0, len(_bindata))
	for name := range _bindata {
		names = append(names, name)
	}
	return names
}

// _bindata is a table, holding each asset generator, mapped to its name.
var _bindata = map[string]func() (*asset, error){
	"home.html": homeHtml,
	"index.html": indexHtml,
	"page.html": pageHtml,
	"post.html": postHtml,
}

// AssetDir returns the file names below a certain
// directory embedded in the file by go-bindata.
// For example if you run go-bindata on data/... and data contains the
// following hierarchy:
//     data/
//       foo.txt
//       img/
//         a.png
//         b.png
// then AssetDir("data") would return []string{"foo.txt", "img"}
// AssetDir("data/img") would return []string{"a.png", "b.png"}
// AssetDir("foo.txt") and AssetDir("notexist") would return an error
// AssetDir("") will return []string{"data"}.
func AssetDir(name string) ([]string, error) {
	node := _bintree
	if len(name) != 0 {
		cannonicalName := strings.Replace(name, "\\", "/", -1)
		pathList := strings.Split(cannonicalName, "/")
		for _, p := range pathList {
			node = node.Children[p]
			if node == nil {
				return nil, fmt.Errorf("Asset %s not found", name)
			}
		}
	}
	if node.Func != nil {
		return nil, fmt.Errorf("Asset %s not found", name)
	}
	rv := make([]string, 0, len(node.Children))
	for childName := range node.Children {
		rv = append(rv, childName)
	}
	return rv, nil
}

type bintree struct {
	Func func() (*asset, error)
	Children map[string]*bintree
}
var _bintree = &bintree{nil, map[string]*bintree{
	"home.html": &bintree{homeHtml, map[string]*bintree{
	}},
	"index.html": &bintree{indexHtml, map[string]*bintree{
	}},
	"page.html": &bintree{pageHtml, map[string]*bintree{
	}},
	"post.html": &bintree{postHtml, map[string]*bintree{
	}},
}}

// RestoreAsset restores an asset under the given directory
func RestoreAsset(dir, name string) error {
        data, err := Asset(name)
        if err != nil {
                return err
        }
        info, err := AssetInfo(name)
        if err != nil {
                return err
        }
        err = os.MkdirAll(_filePath(dir, path.Dir(name)), os.FileMode(0755))
        if err != nil {
                return err
        }
        err = ioutil.WriteFile(_filePath(dir, name), data, info.Mode())
        if err != nil {
                return err
        }
        err = os.Chtimes(_filePath(dir, name), info.ModTime(), info.ModTime())
        if err != nil {
                return err
        }
        return nil
}

// RestoreAssets restores an asset under the given directory recursively
func RestoreAssets(dir, name string) error {
        children, err := AssetDir(name)
        // File
        if err != nil {
                return RestoreAsset(dir, name)
        }
        // Dir
        for _, child := range children {
                err = RestoreAssets(dir, path.Join(name, child))
                if err != nil {
                        return err
                }
        }
        return nil
}

func _filePath(dir, name string) string {
        cannonicalName := strings.Replace(name, "\\", "/", -1)
        return filepath.Join(append([]string{dir}, strings.Split(cannonicalName, "/")...)...)
}

